source_list:
  - SB
  - OL
  - CP
  - ADDR

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data
  file_name: '/receipts_delta_GBR_14_10_2017.csv'

CP:
  s3_conf:
    s3_bucket: vineeth-1
  file_name: '/KC_Extract_1_20171009.csv'


ADDR:
  mongodb_config:
    database: customers
    collection: address

s3_conf:
  s3_bucket: vineeth-1
  staging_dir: pg_staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT

